#!/bin/bash
# Bolt MCP Kali - Sudoers Setup Script
# This configures passwordless sudo for specific security tools

set -e

if [ "$EUID" -ne 0 ]; then
   echo "❌ Please run as root or with sudo"
   exit 1
fi

SUDOERS_FILE="/etc/sudoers.d/mcp-kali"
MCP_USER="${MCP_USER:-kali}"

echo "🔐 Setting up passwordless sudo for MCP Kali tools..."
echo "   User: $MCP_USER"

# Create sudoers file
cat > "$SUDOERS_FILE" << 'EOF'
# Bolt MCP Kali - Passwordless sudo for security tools
# Generated by setup-sudoers.sh

# Network scanning tools
Cmnd_Alias MCP_NETWORK = \
    /usr/bin/nmap, \
    /usr/bin/masscan, \
    /usr/bin/unicornscan, \
    /usr/bin/zmap, \
    /usr/bin/hping3, \
    /usr/sbin/arp-scan, \
    /usr/bin/netdiscover

# Network sniffing tools
Cmnd_Alias MCP_SNIFF = \
    /usr/bin/tcpdump, \
    /usr/bin/wireshark, \
    /usr/bin/tshark, \
    /usr/bin/ettercap

# Wireless tools
Cmnd_Alias MCP_WIRELESS = \
    /usr/sbin/airmon-ng, \
    /usr/sbin/airodump-ng, \
    /usr/sbin/aireplay-ng, \
    /usr/bin/aircrack-ng, \
    /usr/bin/bettercap, \
    /usr/bin/wifite, \
    /usr/bin/reaver

# Network exploitation
Cmnd_Alias MCP_EXPLOIT = \
    /usr/bin/responder, \
    /usr/bin/mitm6

# Allow MCP user to run these tools without password
MCP_USER ALL=(ALL) NOPASSWD: MCP_NETWORK, MCP_SNIFF, MCP_WIRELESS, MCP_EXPLOIT
EOF

# Replace MCP_USER placeholder with actual username
sed -i "s/MCP_USER/$MCP_USER/g" "$SUDOERS_FILE"

# Set correct permissions
chmod 0440 "$SUDOERS_FILE"

# Validate sudoers syntax
if visudo -c -f "$SUDOERS_FILE"; then
    echo "✅ Sudoers configuration created successfully!"
    echo "   File: $SUDOERS_FILE"
    echo ""
    echo "📋 Configured tools:"
    echo "   • Network scanning: nmap, masscan, unicornscan, zmap, hping3"
    echo "   • Network sniffing: tcpdump, wireshark, tshark"
    echo "   • Wireless: aircrack-ng suite, bettercap, wifite"
    echo "   • Exploitation: responder, mitm6"
    echo ""
    echo "🧪 Test with: sudo -l"
else
    echo "❌ Sudoers syntax error! Removing file..."
    rm -f "$SUDOERS_FILE"
    exit 1
fi
