#!/usr/bin/env bun

import solidPlugin from "../node_modules/@cyberstrike-io/tui-solid/scripts/solid-plugin"
import path from "path"
import fs from "fs"
import { $ } from "bun"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import pkg from "../package.json"
import { Script } from "@cyberstrike-io/script"

// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`https://models.dev/api.json`).then((x) => x.text())
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.ts"),
  `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
)
console.log("Generated models-snapshot.ts")

const singleFlag = process.argv.includes("--single")
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")

const allTargets: {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}[] = [
  // ARM64 Linux temporarily disabled - tui-solid has workspace alias resolution issues
  // {
  //   os: "linux",
  //   arch: "arm64",
  // },
  {
    os: "linux",
    arch: "x64",
  },
  {
    os: "linux",
    arch: "x64",
    avx2: false,
  },
  // ARM64 Linux musl temporarily disabled
  // {
  //   os: "linux",
  //   arch: "arm64",
  //   abi: "musl",
  // },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
    avx2: false,
  },
  {
    os: "darwin",
    arch: "arm64",
  },
  {
    os: "darwin",
    arch: "x64",
  },
  {
    os: "darwin",
    arch: "x64",
    avx2: false,
  },
  {
    os: "win32",
    arch: "x64",
  },
  {
    os: "win32",
    arch: "x64",
    avx2: false,
  },
]

const targets = singleFlag
  ? allTargets.filter((item) => {
      if (item.os !== process.platform || item.arch !== process.arch) {
        return false
      }

      // When building for the current platform, prefer a single native binary by default.
      // Baseline binaries require additional Bun artifacts and can be flaky to download.
      if (item.avx2 === false) {
        return baselineFlag
      }

      // also skip abi-specific builds for the same reason
      if (item.abi !== undefined) {
        return false
      }

      return true
    })
  : allTargets

await $`rm -rf dist`

const binaries: Record<string, string> = {}
if (!skipInstall) {
  // Install platform-specific native dependencies needed for cross-compilation
  const PARCEL_WATCHER_VERSION = "2.5.1"
  const OPENTUI_VERSION = "0.1.77"
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${PARCEL_WATCHER_VERSION}`
  // Install opentui native packages for all platforms (needed for cross-compilation)
  await $`bun install @opentui/core-linux-x64@${OPENTUI_VERSION}`
  await $`bun install @opentui/core-darwin-x64@${OPENTUI_VERSION}`
  await $`bun install @opentui/core-darwin-arm64@${OPENTUI_VERSION}`
  await $`bun install @opentui/core-win32-x64@${OPENTUI_VERSION}`
  // Note: tui-core, tui-solid, and spinner are linked from workspace
}
for (const item of targets) {
  const name = [
    "cyberstrike",
    // changing to win32 flags npm for some reason
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi === undefined ? undefined : item.abi,
  ]
    .filter(Boolean)
    .join("-")
  console.log(`building ${name}`)
  await $`mkdir -p dist/${name}/bin`

  const parserWorker = fs.realpathSync(path.resolve(dir, "./node_modules/@cyberstrike-io/tui-core/parser.worker.js"))
  const workerPath = "./src/cli/cmd/tui/worker.ts"

  // Use platform-specific bunfs root path based on target OS
  const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
  const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

  // Build alias map for cross-platform native modules
  const opentuiPlatforms = ["linux-x64", "darwin-x64", "darwin-arm64", "win32-x64"]
  const targetPlatform = `${item.os}-${item.arch}`
  const platformAlias: Record<string, string> = {}
  for (const platform of opentuiPlatforms) {
    // Map all platform imports to target platform for cross-compilation
    platformAlias[`@opentui/core-${platform}`] = `@opentui/core-${targetPlatform}`
  }

  // Plugin to resolve opentui dynamic imports to actual package paths
  const opentuiResolverPlugin: import("bun").BunPlugin = {
    name: "opentui-resolver",
    setup(build) {
      // Handle @opentui/core-* imports
      build.onResolve({ filter: /^@opentui\/core-/ }, (args) => {
        // Always resolve to target platform package
        const pkgName = `@opentui/core-${targetPlatform}`
        const pkgPath = path.resolve(dir, "node_modules", pkgName, "index.js")
        if (fs.existsSync(pkgPath)) {
          return { path: pkgPath }
        }
        // Try package.json main field
        const pkgJsonPath = path.resolve(dir, "node_modules", pkgName, "package.json")
        if (fs.existsSync(pkgJsonPath)) {
          const pkgJson = JSON.parse(fs.readFileSync(pkgJsonPath, "utf-8"))
          const main = pkgJson.main || pkgJson.module || "index.js"
          return { path: path.resolve(dir, "node_modules", pkgName, main) }
        }
        return undefined
      })
    },
  }

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [opentuiResolverPlugin, solidPlugin],
    sourcemap: "external",
    external: ["electron", "chromium-bidi"],
    alias: platformAlias,
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      //@ts-ignore (bun types aren't up to date)
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: name.replace("cyberstrike", "bun") as any,
      outfile: `dist/${name}/bin/cyberstrike`,
      execArgv: [`--user-agent=cyberstrike/${Script.version}`, "--use-system-ca", "--"],
      windows: {},
    },
    entrypoints: ["./src/index.ts", parserWorker, workerPath],
    define: {
      CYBERSTRIKE_VERSION: `'${Script.version}'`,
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      CYBERSTRIKE_WORKER_PATH: workerPath,
      CYBERSTRIKE_CHANNEL: `'${Script.channel}'`,
      CYBERSTRIKE_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
    },
  })

  await $`rm -rf ./dist/${name}/bin/tui`
  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name,
        version: Script.version,
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )
  binaries[name] = Script.version
}

export { binaries }
